### ISSUE TITLE
PR "Sync/Upload for older file, which waits for WiFi too" crash

### ISSUE THREAD

**Issue by hannesa2** [hannesa2/owncloud-android#3] opened 2019-10-19 06:04 UTC
From @pequesan

> Thanks for pointing me to the apk. I've downloaded and installed it (I had to uninstall play store apk first), but I can't pass login page... After introducing my owncloud url and credentials, app crashes and any further try to open it crashes directly.
> 
> Any idea?
> 
> Can I install debug apk and provide you any log?

**Comment by hannesa2** [comment] 2019-10-19 06:06
I don't want to spam upstream repo with support about my fork

**Comment by hannesa2** [comment] 2019-10-19 06:13
@pequesan

A : uninstall. 

My fork has same package name like upstream and other keystore (of course I don't have the origin)
If you want I can change packagename, then you can have both version at the same time on your device

B: crash/log
I made this merged Pull Request #2439 With it you can get log without the need of a debug version.
With https://github.com/owncloud/android/pull/2440 you can make your own investigation easy.

And with https://github.com/owncloud/android/pull/2440#issuecomment-462150721 you see more the the OWncloud log

**Comment by pequesan** [comment] 2019-10-19 07:42
You're right. Best is to keep this conversation here.

I don't need you to change package name. I can uninstall official and install yours. It's not a problem. 

I'm not sure to understand how I can see what's happening if I can't even open the app... Sorry. Can you be more specific?

**Comment by pequesan** [comment] 2019-10-19 10:49
Ok. I've just tried to install again, and this time all is working OK. Can't say what happened yesterday.

I'll keep your fork installed and in case I find any issue related to WiFi sync I'll let you know.

Thanks a tone!!

**Comment by pequesan** [comment] 2019-10-26 23:24
Just for your records, after having to reinstall your apk in a new phone I got yesterday, I've noted that debug apk works OK, while release apk keeps exiting once you put url and credentials...

**Comment by hannesa2** [comment] 2019-10-29 22:02
I fixed a follow up crash and created a new version https://github.com/hannesa2/owncloud-android/releases/tag/2.13.1.s

**Comment by pequesan** [comment] 2019-10-30 07:45
Installed and configured.

Just note that I had to install debug version again. Standard version can't pass auth. App just closes with no FC.

**Comment by hannesa2** [comment] 2019-10-30 21:39
Pleas can you send me the interesting part of the logcat ? You can grab it Settings->protocol.

Unfortunately the haven't implemented Crashlytics. If I do it, I have to publish it in my PlayStore account. It's easy to do, but I'm not sure I've this is a good step

**Comment by pequesan** [comment] 2019-10-31 08:10
Settings->protocol? In Android Settings you mean? I can't find such option. And as I told you, I can't access Owncloud app itself if installed your standard apk.

**Comment by hannesa2** [comment] 2019-10-31 13:42
Here you see how it works https://github.com/owncloud/android/pull/2439#issue-251379114 

Ok, it's called `Settings->Logs`

But I see they changed something, because I gave up with annoying, wrong and pointless pull request wishes https://github.com/owncloud/android/pull/2439#issuecomment-473061893. 
I hope, it will work as expected

**Comment by pequesan** [comment] 2019-10-31 15:36
But... I can't access owncloud app Settings->Logs, because I can't pass initial url & credential screen... With your standard apk I mean... Debug apk is working perfect.

Are we understanding each other? :)

**Comment by hannesa2** [comment] 2019-11-01 17:58
I hope we do.
Now, you can easy investigate what's wrong https://github.com/hannesa2/owncloud-android/releases/tag/2.13.1.s1.

I hope they will ever merge containing pull requests. In the past I was waiting one year !

**Comment by hannesa2** [comment] 2019-11-02 16:47
I fixed an endless-spinner issue in log activity with a new release

**Comment by hannesa2** [comment] 2019-11-02 17:11
sorry, issue still exists

**Comment by pequesan** [comment] 2019-11-04 10:49
Let me explain what happens with debug apk step by step, so you can understand why your last modification doesn't do the job to gain access to log:

- Install debug apk.
- Open app.
- Insert url. Ok
- Insert credentials. App just closes with no FC or anything.
- If I open the app again, it just closes again with no FC or anything.

So... after inserting credentials, I lose the option to see even the initial setup screen... :(

There's no way for me to access app log.

**Comment by hannesa2** [comment] 2019-11-04 11:26
![image](https://user-images.githubusercontent.com/3314607/68117606-18a31500-fefe-11e9-93cd-ad80ff82c760.png)
Please see https://github.com/hannesa2/owncloud-android/releases/tag/2.13.1.s1 
Then you see logs about _previous_ crash

**Comment by hannesa2** [comment] 2019-11-04 11:33
Ok, manual:
Here you find the init
https://github.com/owncloud/android/blob/aba416db49d6494e24050681eb8e78e5bab6e51e/owncloudApp/src/main/java/com/owncloud/android/MainApp.kt#L192

The main question is: Where is your `ExternalStorageDirectory` ? There you find the log file

**Comment by pequesan** [comment] 2019-11-04 11:36
I'll investigate and try to see the log outside the app then.

EDIT: It was easy... just /storage/ownclould/log.

Let me reinstall debug apk and take a look at it.

**Comment by pequesan** [comment] 2019-11-04 11:47
Woops... Good news. I just installed 2.13.1.s3 debug apk and no crash. I've been able to go into the app and do the config. I'll keep this release till your fix is integrated into next owncloud app update.

Thanks!!! :)

**Comment by pequesan** [comment] 2019-11-09 17:21
No so good news in the end... :( I saw your .s4 release, so I tried to install standard apk again, and again I can't pass initial url and login screen. Debug apk no problem.

And again bad news, because it crashes even before it can create its external directory files, so there's no log to give you.

I've compared the initial process with debug apk install, and standard apk crashes just before the moment debug asks for storage permission. Do it help you anyway?

**Comment by hannesa2** [comment] 2019-11-11 07:54
Sorry, when you still have problems with `release`.
But I've the solution
https://github.com/hannesa2/owncloud-android/releases/tag/2.13.1.s6

Additional you get informed on a new version available

**Comment by pequesan** [comment] 2019-11-11 08:01
Good! I can confirm I've installed "release" version with no problems. :)

BTW... if you could merge this feature: https://github.com/owncloud/android/issues/2693 somehow, that would be great!

**Comment by hannesa2** [comment] 2019-11-11 09:55
But in https://github.com/owncloud/android/issues/2693 there is nothing to merge. It's just an issue without code.
And user https://github.com/schwedenmut?tab=repositories has no fork of ownCloud, from where I can cherry-pick something.

Sorry, here I can do nothing

**Comment by pequesan** [comment] 2019-11-11 10:02
You're right... @schwedenmut said there he COULD prepare a patch, but I think he's expecting an answer from someone there before uploading code... You could talk each other there...

I would like to be able to do it myself so no need to bother you...

**Comment by schwedenmut** [comment] 2019-11-11 13:37
Sorry for my late respond. I just onboarded my new job and am quite busy. Will try to provide my cleaned up patch (because what I am currently using is more a "works for me" patch) until the upcoming weekend.

**Comment by hannesa2** [comment] 2019-11-11 20:53
@schwedenmut Make the PR in the first draft dirty, maybe it's [ok](https://www.phrasen.com/andere-kochen-auch-nur-mit-wasser) like it is.

**Comment by pequesan** [comment] 2019-11-14 16:35
@hannesa2, I've seen two more releases from s6, with release notes talking about attemps to fix initial crash... but as I told you, I got rid of it in s6... Did you find another possible bug?

BTW, I've received s9 update message within the app (good!) but I can't install it on top of s6 release version... Is it normal? I should... shouldn't I?

**Comment by hannesa2** [comment] 2019-11-14 22:03
When you are fine, then do nothing.
I investigate a crash on my side

**Comment by hannesa2** [comment] 2019-11-15 13:23
Now I can recommend to update to most recent version https://github.com/hannesa2/owncloud-android/releases

I solved the issue and now I see crashes, if they happen (I hope I see nothing).
I know, it's too late because you/we solved your problem with release start.

**Comment by pequesan** [comment] 2019-11-15 15:10
Now I could upgrade to s91 on top of s6. Good!

**Closed as completed** 2020-12-14 08:08 UTC
